### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Yadro** [rktrlng/pico_tusb_keyboard#1]
Hey, just compiled and it works fine, thanks for the project 👍 

---

**small tip for MacOS users**: to fix upload script you should change target path, like here
```diff
# filename: ./upload

- cp src/${file}.uf2 /media/$USER/RPI-RP2
+ cp src/${file}.uf2 /Volumes/RPI-RP2
```

**Comment by rktrlng** [comment]
Hey, thanks for this!
I wrapped the line in an if statement, to check for OS. It should 'just work' now on both Mac and Linux (untested though).
Thanks again!
